 export const data =  [
    {
      id: 1,
      category: 'fan',
      title: "Royal",
      imgSrc: 'https://imraneshop.com/pub/media/catalog/product/cache/d8b8548ef8c5212cc9f00d4de21c46a9/s/c/screenshot_2_1_3.png',
      price: '89999',
    },
    {
      id: 2,
      category: 'fan',
      title: "khurshid fan",
      imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm3JXsVc2ju5V1MlHvAJXYzdB6W5-XCde3Oz4HukuaIQBZgQyD4zVsC3JaG39_QLFQBLs&usqp=CAU',
      price: '9999',
    },
    {
      id: 3,
      category: 'fan',
      title: "Rado",
      imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm3JXsVc2ju5V1MlHvAJXYzdB6W5-XCde3Oz4HukuaIQBZgQyD4zVsC3JaG39_QLFQBLs&usqp=CAU',
      price: '6000',
    },
    {
      id: 4,
      category: 'fan',
      title: "Leed's",
      imgSrc: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfplETSx3VwlmGEua_tCZC4Sq5yV6eVJMdog&s',
      price: '79999',
    },
    {
      id: 4,
      category: 'fan',
      title: "Pak fan",
      imgSrc: 'https://img.drz.lazcdn.com/static/pk/p/896bc46e199bac4eb41c3a8bde8dd879.jpg_720x720q80.jpg',
      price: '11000',
    },
    {
      id: 5,
      category: 'fan',
      title: "Al-Burj",
      imgSrc: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMnqsP9M35fnjkl3MFWVPdQztpxWzo7XOiLQ&s",
      price: '6999',
    },
    {
      id: 0,
      category: 'laptops',
      title: "Samsung Laptop",
      imgSrc: 'https://mikeshouts.com/wp-content/uploads/2012/01/Samsung-2nd-Generation-Series-9-Laptops-2.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'samsung laptop" (35.5cm) ',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },

{
  id: 10,
  category: 'Vision pro',
  title   :  "vision pro",
  imgSrc: "https://m.media-amazon.com/images/I/41L3p9d4IlL._SX300_SY300_QL70_FMwebp_.jpg",
  amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
  description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
  price:'300000',
},
{
  id: 11,
  category: ' Apple Vision pro',
  title   :  " Apple vision pro",
  imgSrc: "https://photos5.appleinsider.com/gallery/54793-110893-Vision-Pro-xl.jpg",
  amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
  description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
  price:'400000',
},
{
  id: 12,
  category: ' Apple Vision pro',
  title   :  " Apple vision pro",
  imgSrc:  "https://pixelplex.io/wp-content/uploads/2023/09/vision-pro-use-cases-meta.jpg",
  amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
  description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
  price:'400000',
},
{
id: 13,
category: 'L-E-D',
title   :  " Samsung L-E-D",
imgSrc:  "https://i.extremetech.com/imagery/content-types/01WPQcm3dlB9U9vLm0qkt00/hero-image.fit_lim.v1678673098.jpg",
amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
price:'400000',
},
{
  id: 13,
  category: 'L-E-D',
  title   :  " Haier L-E-D",
  imgSrc:  "https://www.theluxurynetwork.com.au/wp-content/uploads/sites/17/2019/10/QLED_4K_DIGITAL-1024x698.jpg",
  amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
  description:' Haier  L-E-D ',
  price:'400000',
  },
  {
    id: 13,
    category: 'L-E-D',
    title   :  " Samsung L-E-D",
    imgSrc:  "https://ichef.bbci.co.uk/ace/ws/640/cpsprodpb/7C57/production/_121313813_hi071518030.jpg.webp",
    amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
    description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
    price:'400000',
    },
    {
      id: 14,
      category: ' Watch',
      title   :  " Smart Watch",
      imgSrc:  "https://shopon.pk/images/detailed/237/61hBxkEW5ZL._AC_SL1500__fmm3-xd.jpg",
      amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
      description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
      price:'400000',
      },
      {
        id: 15,
        category: ' Watch',
        title   :  " Smart Watch",
        imgSrc:  "https://modernwears.pk/wp-content/uploads/2024/05/Untitled-design-2024-08-25T164412.929.jpg",
        amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
        description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
        price:'400000',
        },
        {
          id: 16,
          category: ' Watch',
          title   :  " Smart Watch",
          imgSrc:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfyjspNRBNwABDrzHt2rMI_zMVZ3OUfaQssQ&s",
          amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
          description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
          price:'400000',
          },
  ]