// export const items =
 [
    {
      id: 1,
      category: 'mobiles',
      title: "Apple iPhone 16 pro max",
      imgSrc: 'https://www.apple.com/newsroom/images/2024/09/apple-debuts-iphone-16-pro-and-iphone-16-pro-max/tile/Apple-iPhone-16-Pro-hero-240909-lp.jpg.news_app_ed.jpg',
      amazonLink: 'https://amzn.to/3PuckZp',
      description: 'Apple iPhone 14 (128 GB) - Blue',
      price: '89999',
    },
    {
      id: 5,
      category: 'laptops',
      title: "Apple Laptop",
      imgSrc: 'https://i0.wp.com/www.itinternational.pk/wp-content/uploads/2016/04/apple-macbook-1.jpg?fit=1200%2C900&ssl=1',
      amazonLink: 'https://amzn.to/3EzeQaC',
      description: 'Apple laptop ',
      price: '49999',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Ipad",
      imgSrc: 'https://i.ytimg.com/vi/A5mMaChwCog/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLCUsvmtmQcQlcWB9_4x2BDCr4SYSA',
      amazonLink: 'https://amzn.to/3ZeNRdY',
      description: 'Ipad| Qualcomm Snapdragon 870| ',
      price: '29999',
    },
    {
      id: 2,
      category: 'mobiles',
      title: "Oppo",
      imgSrc: 'https://gsmfloor.pk/wp-content/uploads/Oppo-Reno13-F-4G.jpg',
      amazonLink: 'https://amzn.to/44MiYi6',
      description: 'oppo Reno13 - White',
      price: '79999',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro AMOLED",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3RabsdH',
      description: 'Lenovo Tab P12 Pro AMOLED (12.6 inch (32 cm), 8 GB, 256 GB, Wi-fi Only), Storm Grey with Precision Pen 3',
      price: '19999',
    },
    {
      id: 3,
      category: 'mobiles',
      title: "Samsung",
      imgSrc: "https://m.media-amazon.com/images/I/418KI8X9QBL._AC_.jpg",
      amazonLink: 'https://amzn.to/3r6XJtv',
      description: 'Samsung S25 urtra - Blue',
      price: '69999',
    },
    {
      id: 4,
      category: 'laptops',
      title: "Samsung Laptop",
      imgSrc: 'https://mikeshouts.com/wp-content/uploads/2012/01/Samsung-2nd-Generation-Series-9-Laptops-2.jpg',
      amazonLink: 'https://amzn.to/44JsK4r',
      description: 'samsung laptop" (35.5cm) ',
      price: '29999',
    },
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
      amazonLink: 'https://amzn.to/3Pdsh4F',
      description: 'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, RAM 4 GB, ROM 64 GB Expandable, Wi-Fi Tablet, Gray, (SM-X200NZAEINU)',
      price: '49999',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      amazonLink: 'https://amzn.to/3r9rvhm',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
    },

{
  id: 10,
  category: 'Vision pro',
  title   :  "vision pro",
  imgSrc: "https://m.media-amazon.com/images/I/41L3p9d4IlL._SX300_SY300_QL70_FMwebp_.jpg",
  amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
  description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
  price:'300000',
},
{
  id: 11,
  category: ' Apple Vision pro',
  title   :  " Apple vision pro",
  imgSrc: "https://photos5.appleinsider.com/gallery/54793-110893-Vision-Pro-xl.jpg",
  amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
  description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
  price:'400000',
},
{
  id: 12,
  category: ' Apple Vision pro',
  title   :  " Apple vision pro",
  imgSrc:  "https://pixelplex.io/wp-content/uploads/2023/09/vision-pro-use-cases-meta.jpg",
  amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
  description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
  price:'400000',
},
{
id: 13,
category: 'L-E-D',
title   :  " Samsung L-E-D",
imgSrc:  "https://i.extremetech.com/imagery/content-types/01WPQcm3dlB9U9vLm0qkt00/hero-image.fit_lim.v1678673098.jpg",
amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
price:'400000',
},
{
  id: 13,
  category: 'L-E-D',
  title   :  " Haier L-E-D",
  imgSrc:  "https://www.theluxurynetwork.com.au/wp-content/uploads/sites/17/2019/10/QLED_4K_DIGITAL-1024x698.jpg",
  amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
  description:' Haier  L-E-D ',
  price:'400000',
  },
  {
    id: 13,
    category: 'L-E-D',
    title   :  " Samsung L-E-D",
    imgSrc:  "https://ichef.bbci.co.uk/ace/ws/640/cpsprodpb/7C57/production/_121313813_hi071518030.jpg.webp",
    amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
    description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
    price:'400000',
    },
    {
      id: 14,
      category: ' Watch',
      title   :  " Smart Watch",
      imgSrc:  "https://shopon.pk/images/detailed/237/61hBxkEW5ZL._AC_SL1500__fmm3-xd.jpg",
      amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
      description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
      price:'400000',
      },
      {
        id: 15,
        category: ' Watch',
        title   :  " Smart Watch",
        imgSrc:  "https://modernwears.pk/wp-content/uploads/2024/05/Untitled-design-2024-08-25T164412.929.jpg",
        amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
        description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
        price:'400000',
        },
        {
          id: 16,
          category: ' Watch',
          title   :  " Smart Watch",
          imgSrc:  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfyjspNRBNwABDrzHt2rMI_zMVZ3OUfaQssQ&s",
          amazonLink: 'https://m.media-amazon.com/images/I/71dnQnYLOsL._SX466_.jpg',
          description:' Vision Pro, Quest 3/2/1, Rift S, Valve Index, Pico 4 ',
          price:'400000',
          },
  ]